name: Unzip File

on:
  push:
    paths:
      - "*.zip"  # Kích hoạt workflow khi có file ZIP được push lên

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip files
        run: |
          for file in *.zip; do
            unzip -o "$file" -d ./extracted/
          done

      - name: Push extracted files
        run: |
          git config --global user.name "Mtruong12345"
          git config --global user.email "minhletruong65@gmail.com"
          git add .
          git commit -m "Profile-ThanhDieu.Com-V5-Tester-main.zip"
          git push
